### PR TITLE
AWS SQS 5.3.0

### PR DESCRIPTION
**Pull request by mauro-dentoni**

### CODE REVIEW

**Comment by wwarner-salesforce** [comment]
Tentative release date: week of April 8-12.

**Comment by wwarner-salesforce** [comment]
See also https://github.com/mulesoft/docs-connectors/pull/143

**Comment by xidex** [comment]
See also: https://github.com/mulesoft/docs-release-notes/pull/556

**Comment by xidex** [comment]
This needs to be merged **first**: https://github.com/mulesoft/docs-release-notes/pull/536

**Comment by wwarner-salesforce** [comment]
Date needs to be added before merging.

**Comment by mauro-dentoni** [comment]
@wwarner-salesforce this connector was also released today. You can review and merge the docs. Thanks!!

**Comment by wwarner-salesforce** [comment]
Thank you, Mauro! https://github.com/mulesoft/docs-release-notes/pull/536 and https://github.com/mulesoft/docs-connectors/pull/143 are merged. Date is added.

**Pull request merged**
