### PR TITLE
AWS SNS 4.2.0 (Do not merge until release, or without adding release date)

### PR DESCRIPTION
**Pull request by mauro-dentoni**

### CODE REVIEW

**Comment by wwarner-salesforce** [comment]
Tentative release date: week of April 15-19.

**Comment by wwarner-salesforce** [comment]
Goes with https://github.com/mulesoft/docs-connectors/pull/145

**Comment by mauro-dentoni** [comment]
@wwarner-salesforce This connector was released today. You can review and merge the docs. Thanks!!

**Comment by wwarner-salesforce** [comment]
Thank you, Mauro!

**Pull request merged**
