### PR TITLE
APM 1.26.1 relnotes

### PR DESCRIPTION
**Pull request by IanWhyte**

### CODE REVIEW

**Comment by IanWhyte** [comment]
I updated the PR to incorp your edits - pls review - thx.

**Comment by mcherem** [comment]
Thanks Ian. I am new to the process, so please let me know if there is
anything else I need to do.
Regards,
~Maria

**Comment by IanWhyte** [comment]
Thanks, Maria - if you approve, would you merge the pull request, please?

**Comment by mcherem** [comment]
Done!

**Pull request merged**
