### PR TITLE
AWS S3 5.3.0 (Do not merge until release, or without adding release date)

### PR DESCRIPTION
**Pull request by mauro-dentoni**

### CODE REVIEW

**Comment by wwarner-salesforce** [comment]
Tentative release date: week of April 8-12.

**Comment by xidex** [comment]
Goes with: https://github.com/mulesoft/docs-connectors/pull/142

**Comment by xidex** [comment]
This needs to be merged **first**: mulesoft/docs-release-notes#556

**Comment by wwarner-salesforce** [comment]
@xidex @gastonbritomulesoft This PR was merged without replacing "*Date to be determined.*" with today's date, and that incorrect information was briefly published on the public docs website until it was corrected in https://github.com/mulesoft/docs-release-notes/pull/563 . Note that the title of the PR says "Do not merge until release, or without adding release date." In the future, please be careful not to merge PRs without adding the required info. We may soon institute a requirement that docs PRs can only be merged by a member of the docs team.

**Pull request merged**
